Repository depromeet/14th-team4-BE, pull requests merged in 2024-01, with the labels that each got.

#15 Feature/#15
  server-common/build.gradle
  server-common/src/main/resources/logback/logback-develop.xml
  server-common/src/main/resources/logback/logback-local.xml
  server-common/src/main/resources/logback/logback-release.xml
  server-common/src/main/resources/logging.yml
Labels: ✨feature, ⚒️ fix

#14 [Feature/#20] Rest Docs 최적화 및 enum 타입 설정, spring security 테스트 실패 해결, 노션 가이드라인 제공
  .gitignore
  server-api/build.gradle
  server-api/src/docs/asciidoc/Home.adoc
  server-api/src/docs/asciidoc/Member-API.adoc
  server-api/src/docs/asciidoc/common/test-member-status.adoc
  server-api/src/docs/asciidoc/common/test-sex.adoc
  server-api/src/docs/asciidoc/index.adoc
  server-api/src/docs/asciidoc/test.adoc
  server-api/src/main/java/com/depromeet/config/SecurityConfig.java
  server-api/src/main/java/com/depromeet/domains/home/controller/HomeController.java
  server-api/src/main/java/com/depromeet/domains/test/controller/TestController.java
  server-api/src/main/java/com/depromeet/domains/test/dto/request/TestMemberSignUpRequest.java
  server-api/src/main/java/com/depromeet/domains/test/dto/request/TestRequest.java
  server-api/src/main/java/com/depromeet/domains/test/dto/response/TestEnum.java
  server-api/src/main/java/com/depromeet/domains/test/dto/response/TestMemberResponse.java
  server-api/src/main/java/com/depromeet/domains/test/dto/response/TestResponse.java
  server-api/src/main/java/com/depromeet/domains/test/service/TestService.java
  server-api/src/main/resources/static/docs/common/test-member-status.html
  server-api/src/main/resources/static/docs/common/test-sex.html
  server-api/src/main/resources/static/docs/index.html
  server-api/src/test/java/com/depromeet/controller/HomeControllerTest.java
  server-api/src/test/java/com/depromeet/controller/TestControllerTest.java
  server-api/src/test/java/com/depromeet/controller/TestMemberController.java
  server-api/src/test/java/com/depromeet/controller/TestMemberControllerTest.java
  server-api/src/test/java/com/depromeet/document/CommonDocController.java
  server-api/src/test/java/com/depromeet/document/CommonDocControllerTest.java
  server-api/src/test/java/com/depromeet/document/ControllerTest.java
  server-api/src/test/java/com/depromeet/document/DocumentLinkGenerator.java
  server-api/src/test/java/com/depromeet/document/EnumDocs.java
  server-domain/src/main/java/com/depromeet/test/Person.java
  server-domain/src/main/java/com/depromeet/test/TestEnumType.java
  server-domain/src/main/java/com/depromeet/test/TestMember.java
  server-domain/src/main/java/com/depromeet/test/TestMemberRepository.java
  server-domain/src/main/java/com/depromeet/test/TestMemberStatus.java
Labels: 📝 chore, ⚒️ fix, ♻️ refactor

#13 [ Feature/#25 ] 토큰 갱신 기능 추가, 로그인 리팩토링
  server-api/build.gradle
  server-api/src/main/java/com/depromeet/annotation/AuthUser.java
  server-api/src/main/java/com/depromeet/auth/controller/AuthController.java
  server-api/src/main/java/com/depromeet/auth/dto/TokenResponse.java
  server-api/src/main/java/com/depromeet/auth/jwt/JwtAuthenticationFilter.java
  server-api/src/main/java/com/depromeet/auth/jwt/JwtService.java
  server-api/src/main/java/com/depromeet/auth/oauth2/CustomOAuth2User.java
  server-api/src/main/java/com/depromeet/auth/oauth2/handler/CustomOAuth2FailureHandler.java
  server-api/src/main/java/com/depromeet/auth/oauth2/service/CustomOAuth2UserService.java
  server-api/src/main/java/com/depromeet/auth/service/AuthService.java
  server-api/src/main/java/com/depromeet/auth/service/RedisService.java
  server-api/src/main/java/com/depromeet/config/RedisConfig.java
  server-api/src/main/java/com/depromeet/config/SecurityConfig.java
  server-api/src/main/java/com/depromeet/domains/home/controller/HomeController.java
  server-domain/src/main/java/com/depromeet/domains/common/entity/BaseTimeEntity.java
  server-domain/src/main/java/com/depromeet/domains/user/repository/UserRepository.java
Labels: ✨feature, ⚒️ fix, ♻️ refactor

#19 [ Feature/#33 ] NCP(s3) object storage presigned url 발급 API 추가
  server-api/build.gradle
  server-api/src/main/java/com/depromeet/domains/image/controller/ImageController.java
  server-infra/build.gradle
  server-infra/src/main/java/com/depromeet/S3/S3Config.java
  server-infra/src/main/java/com/depromeet/S3/S3UploaderService.java
Labels: ✨feature

#22 [Feature/#42] 리뷰 작성 API 추가
  server-api/src/docs/asciidoc/index.adoc
  server-api/src/docs/asciidoc/store.adoc
  server-api/src/main/java/com/depromeet/domains/store/controller/StoreController.java
  server-api/src/main/java/com/depromeet/domains/store/dto/request/NewStoreRequest.java
  server-api/src/main/java/com/depromeet/domains/store/dto/request/ReviewRequest.java
  server-api/src/main/java/com/depromeet/domains/store/dto/response/ReviewAddResponse.java
  server-api/src/main/java/com/depromeet/domains/store/dto/response/StoreReviewResponse.java
  server-api/src/main/java/com/depromeet/domains/store/service/StoreService.java
  server-api/src/test/java/com/depromeet/controller/StoreControllerTest.java
  server-api/src/test/java/com/depromeet/controller/UserControllerTest.java
  server-common/src/main/java/com/depromeet/common/exception/CustomResponseEntity.java
  server-common/src/main/java/com/depromeet/common/exception/Result.java
  server-domain/src/main/java/com/depromeet/domains/review/entity/Review.java
  server-domain/src/main/java/com/depromeet/domains/store/entity/Store.java
  server-domain/src/main/java/com/depromeet/domains/store/entity/StoreLocation.java
  server-infra/src/main/resources/application-infra-develop.yml
  server-infra/src/main/resources/application-infra-local.yml
  server-infra/src/main/resources/application-infra-release.yml
  server-infra/src/main/resources/application-infra.yml
Labels: ✨feature, 📄 docs

#25 [Feature/#37] 로그인 인증 관련 로직 추가
  server-api/src/main/java/com/depromeet/auth/controller/AuthController.java
  server-api/src/main/java/com/depromeet/auth/jwt/JwtService.java
  server-api/src/main/java/com/depromeet/auth/oauth2/CustomOAuth2User.java
  server-api/src/main/java/com/depromeet/auth/oauth2/OAuth2Attribute.java
  server-api/src/main/java/com/depromeet/auth/oauth2/handler/CustomOAuth2FailureHandler.java
  server-api/src/main/java/com/depromeet/auth/oauth2/handler/CustomOAuth2SuccessHandler.java
  server-api/src/main/java/com/depromeet/auth/oauth2/service/CustomOAuth2UserService.java
  server-api/src/main/java/com/depromeet/auth/service/AuthService.java
  server-api/src/main/java/com/depromeet/auth/service/CookieService.java
  server-api/src/main/java/com/depromeet/config/SecurityConfig.java
  server-common/src/main/java/com/depromeet/common/exception/Result.java
  server-domain/src/main/java/com/depromeet/domains/user/entity/User.java
  server-domain/src/main/java/com/depromeet/domains/user/repository/UserRepository.java
  server-domain/src/main/java/com/depromeet/enums/Role.java
  server-domain/src/main/java/com/depromeet/enums/UserLevel.java
  server-domain/src/main/resources/data.sql
Labels: ⚒️ fix, ♻️ refactor

#27 feature/#49 [Chore] logback-local.xml 설정에서 슬랙설정 삭제
  server-common/src/main/resources/logback/logback-local.xml
Labels: ⚒️ fix

#39 [Feature/#67] 내 북마크, 내 리뷰 반환값 변경
  server-api/src/docs/asciidoc/index.adoc
  server-api/src/main/java/com/depromeet/domains/user/dto/response/UserBookmarkResponse.java
  server-api/src/main/java/com/depromeet/domains/user/dto/response/UserReviewResponse.java
  server-api/src/main/java/com/depromeet/domains/user/service/UserService.java
  server-api/src/test/java/com/depromeet/controller/AuthControllerTest.java
  server-api/src/test/java/com/depromeet/controller/UserControllerTest.java
Labels: 📄 docs, ⚒️ fix

#40 [Feature/#70] 음식점, 카페 통합 검색시 카카오로 부터 응답받는 category_name의 경우에 따른 조건문 처리
  server-api/src/docs/asciidoc/index.adoc
  server-api/src/main/java/com/depromeet/domains/store/controller/StoreController.java
  server-api/src/main/java/com/depromeet/domains/store/service/StoreSearchService.java
  server-api/src/main/java/com/depromeet/domains/store/service/StoreService.java
  server-domain/src/main/java/com/depromeet/domains/review/entity/Review.java
  server-domain/src/main/java/com/depromeet/domains/review/repository/ReviewRepository.java
  server-domain/src/main/java/com/depromeet/domains/store/entity/StoreMeta.java
  server-domain/src/main/resources/data.sql
Labels: ⚒️ fix

#47 [fix] 맵api response에 categoryType 수정함, 조건에 맞는 식당들 정보 호출시 리뷰수 역순(DESC) 추가
  server-api/http/StoreController.http
  server-api/src/main/java/com/depromeet/domains/store/service/StoreService.java
  server-domain/src/main/java/com/depromeet/domains/store/repository/StoreRepository.java
Labels: ⚒️ fix

#54 [ Feature/#84] 닉네임 중복 검사 추가
  server-api/src/main/java/com/depromeet/domains/user/service/UserService.java
  server-common/src/main/java/com/depromeet/common/exception/Result.java
Labels: ⚒️ fix

#53 [Feature/#81] 사용자 리뷰 작성 가능 여부 체크 API 추가
  server-api/src/main/java/com/depromeet/domains/store/controller/StoreController.java
  server-api/src/main/java/com/depromeet/domains/store/dto/response/ReviewAddLimitResponse.java
  server-api/src/main/java/com/depromeet/domains/store/service/StoreService.java
  server-api/src/test/java/com/depromeet/controller/StoreControllerTest.java
  server-domain/src/main/java/com/depromeet/domains/review/repository/ReviewRepository.java
Labels: ✨feature

#59 [Feature/#86] 로그아웃, 회원탈퇴 API 추가
  server-api/src/docs/asciidoc/index.adoc
  server-api/src/main/java/com/depromeet/auth/controller/AuthController.java
  server-api/src/main/java/com/depromeet/auth/dto/TokenResponse.java
  server-api/src/main/java/com/depromeet/auth/jwt/JwtAuthenticationFilter.java
  server-api/src/main/java/com/depromeet/auth/jwt/JwtService.java
  server-api/src/main/java/com/depromeet/auth/service/AuthService.java
  server-api/src/main/java/com/depromeet/auth/service/CookieService.java
  server-api/src/main/java/com/depromeet/auth/service/RedisService.java
  server-api/src/main/java/com/depromeet/domains/user/controller/UserController.java
  server-api/src/main/java/com/depromeet/domains/user/service/UserService.java
  server-api/src/test/java/com/depromeet/controller/AuthControllerTest.java
  server-api/src/test/java/com/depromeet/controller/UserControllerTest.java
  server-api/src/test/java/com/depromeet/document/ControllerTest.java
  server-common/src/main/java/com/depromeet/common/exception/Result.java
  server-domain/src/main/java/com/depromeet/domains/user/entity/User.java
Labels: ✨feature
